name: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semantic_pull_request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: "**/*.md"
      modified_files_only: false

  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Checkout
        uses: actions/checkout@v4

      - name: 🐦 Setup Flutter with FVM
        uses: kuhnroyal/flutter-fvm-config-action@v2

      - name: 📦 Install Dependencies
        run: dart pub get

      - name: ✨ Check Formatting
        run: dart format --set-exit-if-changed .

      - name: 🔍 Analyze
        run: dart analyze

      - name: 🧪 Run Tests
        run: dart test

